[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scbiot"
authors = [{name = "Haihui Zhang", email = "hanfei19@gmail.com"}]
dynamic = ["version", "description"]
